name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly]

    env:
      CRATE_NAME: cargo-nono

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust }}

    - name: Build and test
      run: bash ci/script.sh

    - name: Deploy
      if: startsWith(github.ref, 'refs/tags/')
      run: bash ci/before_deploy.sh && cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      with:
        files: ${{ env.CRATE_NAME }}-${{ github.ref_name }}-${{ matrix.os }}.*
        token: ${{ secrets.GITHUB_TOKEN }}
